### ISSUE TITLE
Referanse sendes som null til bidrag-vedtak ved direkte oppgjør.

### ISSUE THREAD

**Issue by simhos** [navikt/bidrag-regnskap#25]
Se sakid 2300287

Bidrag-vedtak mottar null på feltet referanse som fører til at vedtaket ikke blir lagt ut på bidrag-vedtak topic for videre behandling av bidrag-stonad og bidrag-regnskap. Dette er fikset for gebyrer. Burde også vurdere om det må gjøres noe i andre engangsbeløp.

**Comment by morher** [comment]
Løst i Bisys.
